//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int aboutID { get; set; }
        public string aboutCaption { get; set; }
        public string aboutHeader { get; set; }
        public string aboutLinks { get; set; }
        public Nullable<bool> activity { get; set; }
    }
}
