//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AltSlider
    {
        public int AltSliderID { get; set; }
        public string Baslik { get; set; }
        public string OzetMetin { get; set; }
        public string ImgUrl { get; set; }
        public string TamMetin { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        public Nullable<bool> aktiflikDurumu { get; set; }
        public Nullable<int> SiraNo { get; set; }
    }
}
