//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealOfTheMonth
    {
        public int dealID { get; set; }
        public string dealHeader { get; set; }
        public string dealCaption { get; set; }
        public string dealImage { get; set; }
        public Nullable<bool> activity { get; set; }
    }
}
