//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webSiteDemoEntities1 : DbContext
    {
        public webSiteDemoEntities1()
            : base("name=webSiteDemoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LogType> LogType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserAuthorization> UserAuthorization { get; set; }
        public virtual DbSet<UserLog> UserLog { get; set; }
        public virtual DbSet<About> About { get; set; }
        public virtual DbSet<AltSlider> AltSlider { get; set; }
        public virtual DbSet<DealOfTheMonth> DealOfTheMonth { get; set; }
        public virtual DbSet<Navbar> Navbar { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Product> Product { get; set; }
    }
}
