//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Navbar
    {
        public int navbarID { get; set; }
        public Nullable<bool> aktivity { get; set; }
        public Nullable<int> queueNo { get; set; }
        public string header { get; set; }
        public string icons { get; set; }
        public string logo { get; set; }
    }
}
