//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int poductID { get; set; }
        public string productName { get; set; }
        public string shortCaption { get; set; }
        public string productPrice { get; set; }
        public string productImage { get; set; }
        public Nullable<int> productOrderID { get; set; }
        public Nullable<bool> activity { get; set; }
        public Nullable<int> productQueue { get; set; }
    }
}
