//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int LogID { get; set; }
        public Nullable<int> LogTypeID { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string PCIP { get; set; }
        public string LogCaption { get; set; }
        public Nullable<int> LogUserID { get; set; }
    
        public virtual LogType LogType { get; set; }
    }
}
